// Code generated by Kitex v0.6.1. DO NOT EDIT.

package videoservice

import (
	"context"
	video "douyinv2/video/kitex_gen/video"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	VideoPublish(ctx context.Context, req *video.VideoPublishRequest, callOptions ...callopt.Option) (r *video.VideoPublishResponse, err error)
	GetVideoList(ctx context.Context, req *video.VideoPublishedListRequest, callOptions ...callopt.Option) (r *video.VideoPublishedListResponse, err error)
	Feed(ctx context.Context, req *video.FeedRequest, callOptions ...callopt.Option) (r *video.FeedResponse, err error)
	LikeAction(ctx context.Context, req *video.FavoriteActionRequest, callOptions ...callopt.Option) (r *video.FavoriteActionResponse, err error)
	LikeVideos(ctx context.Context, req *video.FavoriteVideoListRequest, callOptions ...callopt.Option) (r *video.FavoriteVideoListResponse, err error)
	IfLike(ctx context.Context, req *video.DoesFavoriteRequest, callOptions ...callopt.Option) (r *video.DoesFavoriteResponse, err error)
	CommentACtion(ctx context.Context, req *video.CommentActionRequest, callOptions ...callopt.Option) (r *video.CommentActionResponse, err error)
	CommentList(ctx context.Context, req *video.CommentListRequest, callOptions ...callopt.Option) (r *video.CommentListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) VideoPublish(ctx context.Context, req *video.VideoPublishRequest, callOptions ...callopt.Option) (r *video.VideoPublishResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VideoPublish(ctx, req)
}

func (p *kVideoServiceClient) GetVideoList(ctx context.Context, req *video.VideoPublishedListRequest, callOptions ...callopt.Option) (r *video.VideoPublishedListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoList(ctx, req)
}

func (p *kVideoServiceClient) Feed(ctx context.Context, req *video.FeedRequest, callOptions ...callopt.Option) (r *video.FeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, req)
}

func (p *kVideoServiceClient) LikeAction(ctx context.Context, req *video.FavoriteActionRequest, callOptions ...callopt.Option) (r *video.FavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeAction(ctx, req)
}

func (p *kVideoServiceClient) LikeVideos(ctx context.Context, req *video.FavoriteVideoListRequest, callOptions ...callopt.Option) (r *video.FavoriteVideoListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeVideos(ctx, req)
}

func (p *kVideoServiceClient) IfLike(ctx context.Context, req *video.DoesFavoriteRequest, callOptions ...callopt.Option) (r *video.DoesFavoriteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.IfLike(ctx, req)
}

func (p *kVideoServiceClient) CommentACtion(ctx context.Context, req *video.CommentActionRequest, callOptions ...callopt.Option) (r *video.CommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentACtion(ctx, req)
}

func (p *kVideoServiceClient) CommentList(ctx context.Context, req *video.CommentListRequest, callOptions ...callopt.Option) (r *video.CommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentList(ctx, req)
}
