// Code generated by hertz generator.

package main

import (
	"context"
	"douyinv2/biz/mw"
	"douyinv2/biz/rpc"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	rpc.Init()
	mw.InitJwtMiddleWare()
	h := server.Default()
	h.GET("/movies/:filemovie", func(ctx context.Context, c *app.RequestContext) {
		filemovie := c.Param("filemovie")
		c.File("./movies/" + filemovie)
	})
	h.GET("/photo/:photo", func(ctx context.Context, c *app.RequestContext) {
		filephoto := c.Param("photo")
		c.File("./photo/" + filephoto)
	})
	register(h)
	h.Spin()
}
