// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserFollow = "user_follows"

// UserFollow mapped from table <user_follows>
type UserFollow struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	FromID    int64          `gorm:"column:from_id" json:"from_id"`
	ToID      int64          `gorm:"column:to_id" json:"to_id"`
}

// TableName UserFollow's table name
func (*UserFollow) TableName() string {
	return TableNameUserFollow
}
