// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	douyinv2 "douyinv2/biz/router/douyinv2"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	douyinv2.Register(r)
}
